### ISSUE TITLE
Connection fails unhelpfully when no database name is given

### ISSUE THREAD

**Issue by eatonphil** [briansteffens/sql#1]
My config.json:

```json
{
        "driver": "mysql",
        "host": "db.local",
        "port": 3306,
        "user": "root",
        "password": "",
        "database": ""
}
```

There is an entry for db.local in my hosts file.

The output when running prequel.

```
panic: invalid DSN: missing the slash separating the database name

goroutine 1 [running]:
panic(0x1f8300, 0xc42000cb80)
        /usr/local/Cellar/go/1.7.4_2/libexec/src/runtime/panic.go:500 +0x1a1
main.main()
        /Users/peaton/.go/src/github.com/briansteffens/prequel/prequel.go:259 +0x5fe
```

**Comment by eatonphil** [comment]
Whoops. The real issue is that there is no database specified and it expects one.

**Comment by briansteffens** [comment]
It gives a better error message now (same if driver is missing).
